// Generated by tools/compile-cloud-transport.ts. Do not edit.
const COMPILED_CLOUD_WORLD_SCALE:vec3f=vec3f(0.00062,0.00062,0.00062);
const COMPILED_CLOUD_WIND_SCALE:vec3f=vec3f(-0.00062,0.0,-0.00062);
fn compiledCloudCoordinates(world:vec3f,windTime:vec3f)->vec3f {
  return world*COMPILED_CLOUD_WORLD_SCALE+windTime*COMPILED_CLOUD_WIND_SCALE;
}
fn compiledCloudMotion(previousWindTime:vec3f,currentWindTime:vec3f)->vec3f {
  return (currentWindTime-previousWindTime)*vec3f(1.0,0.0,1.0);
}
// Integral on [0,1] of clamp(a+(b-a)*s,0,1), including support crossings.
fn compiledCloudDensityIntegral(a:f32,b:f32)->f32 {
  let low=min(a,b);let high=max(a,b);let delta=high-low;
  if(high<=0.0) {return 0.0;}
  if(low>=1.0) {return 1.0;}
  if(delta<0.00001) {return clamp(0.5*(a+b),0.0,1.0);}
  let start=clamp(-low/delta,0.0,1.0);
  let end=clamp((1.0-low)/delta,0.0,1.0);
  return 0.5*(clamp(low,0.0,1.0)+clamp(high,0.0,1.0))*(end-start)+1.0-end;
}
// A projected line is fractional-linear in depth. Its derivative has constant
// sign while the denominator stays positive, so endpoints enclose its image.
fn compiledCloudProjectionRadius(nearPoint:vec3f,meanPoint:vec3f,farPoint:vec3f,
  right:vec3f,up:vec3f,forward:vec3f,scale:vec2f)->f32 {
  let z=vec3f(dot(nearPoint,forward),dot(meanPoint,forward),dot(farPoint,forward));
  if(any(z<=vec3f(0.001))) {return 1e10;}
  let a=vec2f(dot(nearPoint,right),dot(nearPoint,up))/z.x*scale;
  let b=vec2f(dot(meanPoint,right),dot(meanPoint,up))/z.y*scale;
  let c=vec2f(dot(farPoint,right),dot(farPoint,up))/z.z*scale;
  return max(length(a-b),length(c-b));
}
