import { radianceLightingWGSL } from "./radiance-lighting";
import { createAtmosphereWGSL } from "./atmosphere";
import brdf from "./brdf.wgsl" with { type: "text" };
import creatureMaterial from "./creature-material.wgsl" with { type: "text" };
import display from "./display.wgsl" with { type: "text" };
import { createFiniteSunWGSL } from "./finite-sun";
import foliage from "./foliage.wgsl" with { type: "text" };
import indirect from "./indirect.wgsl" with { type: "text" };
import { localLightingWGSL } from "./local-lighting";
import materialLattice from "./material-lattice.wgsl" with { type: "text" };
import primitive from "./primitive.wgsl" with { type: "text" };
import source from "./scene.wgsl" with { type: "text" };
import surfaceAppearance from "./surface-appearance.wgsl" with { type: "text" };
import surfaceRelief from "./surface-relief.wgsl" with { type: "text" };
import thinCoverage from "./thin-coverage.wgsl" with { type: "text" };
import water from "./water.wgsl" with { type: "text" };
import waterBody from "./water-body.wgsl" with { type: "text" };
import { createWaterBudgetWGSL } from "./water-budget";
import waterGlints from "./water-glints.wgsl" with { type: "text" };
import waterTransport from "./water-transport.wgsl" with { type: "text" };
import wovenMaterial from "./woven-material.wgsl" with { type: "text" };
export const shader = `${source}\n${localLightingWGSL}\n${wovenMaterial}\n${materialLattice}\n${creatureMaterial}\n${foliage}\n${surfaceAppearance}\n${surfaceRelief}\n${thinCoverage}\n${indirect}\n${radianceLightingWGSL}\n${brdf}\n${waterTransport}\n${createWaterBudgetWGSL()}\n${water}\n${waterBody}\n${waterGlints}\n${primitive}\n${createFiniteSunWGSL(0, 3)}\n${createAtmosphereWGSL(0, 4)}`;
export const displayShader = display;
