// Generated by tools/compiler-frontiers/build-material.ts. Source 8348c8a228bd3a21.
// Albedo coverage only. Exact for affine phase footprints in real arithmetic.
const WOVEN_MODE:u32=0u;
fn wovenSinc(x:f32)->f32 {if(abs(x)<0.0001){return 1.0-x*x/6.0;}return sin(x)/x;}
fn wovenMode(k:vec2f,phase:vec2f,dx:vec2f,dy:vec2f)->f32 {
 return cos(dot(k,phase))*wovenSinc(dot(k,dx)*0.5)*wovenSinc(dot(k,dy)*0.5);
}
fn wovenCoverage(phase:vec2f,dx:vec2f,dy:vec2f)->f32 {
 if(WOVEN_MODE==1u){return (0.5+0.5*cos(phase.x))*(0.5+0.5*cos(phase.y));}
 if(WOVEN_MODE>=2u){
   var sum=0.0;let count=select(32u,64u,WOVEN_MODE==3u);
   for(var y=0u;y<count;y++){for(var x=0u;x<count;x++){
     let p=phase+((f32(x)+0.5)/f32(count)-0.5)*dx+((f32(y)+0.5)/f32(count)-0.5)*dy;
     sum+=(0.5+0.5*cos(p.x))*(0.5+0.5*cos(p.y));
   }}return sum/f32(count*count);
 }
 var value=0.25;
  value+=0.25*wovenMode(vec2f(0.0,1.0),phase,dx,dy);
  value+=0.25*wovenMode(vec2f(1.0,0.0),phase,dx,dy);
  value+=0.125*wovenMode(vec2f(1.0,1.0),phase,dx,dy);
  value+=0.125*wovenMode(vec2f(1.0,-1.0),phase,dx,dy);
 return clamp(value,0.0,1.0);
}
