// Builds the runtime into dist/: the bootstrap page, the main-thread shim and the render worker.
// dist/ is committed, so `wrela build` can ship it without a JavaScript toolchain; `--check`
// fails if dist/ isn't exactly what this build makes from src/ (CI runs it). Both fail if the
// runtime is over its 1 MB budget (D-069). The output is deterministic: the same sources and
// esbuild version give the same bytes.
//
//   bun scripts/build.ts            write dist/
//   bun scripts/build.ts --check    compare dist/ with a fresh build; write nothing

import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";
import * as esbuild from "esbuild";

/** D-069's runtime budget, in bytes (1 MB, not MiB). */
const BUDGET = 1_000_000;

const root = join(import.meta.dir, "..");
const dist = join(root, "dist");
const check = process.argv.includes("--check");

const result = await esbuild.build({
  absWorkingDir: root,
  entryPoints: { wrela: "src/main.ts", "wrela-worker": "src/worker.ts" },
  outdir: "dist",
  bundle: true,
  format: "esm",
  platform: "browser",
  // Chrome 113 (WebGPU's first release) runs ES2022.
  target: "es2022",
  charset: "utf8",
  legalComments: "none",
  banner: {
    js: "// Generated by runtime/browser/scripts/build.ts from runtime/browser/src; don't edit.",
  },
  write: false,
  logLevel: "warning",
});

const outputs = new Map<string, Uint8Array>();
for (const file of result.outputFiles) {
  outputs.set(relative(dist, file.path), file.contents);
}
outputs.set("index.html", await readFile(join(root, "src/index.html")));

const total = [...outputs.values()].reduce((n, bytes) => n + bytes.length, 0);
const sizes = [...outputs].map(([name, bytes]) => `${name} ${bytes.length}`).join(", ");
if (total > BUDGET) {
  console.error(`the runtime is ${total} bytes, over its ${BUDGET}-byte budget (D-069): ${sizes}`);
  process.exit(1);
}

async function existing(): Promise<string[]> {
  try {
    return await readdir(dist);
  } catch {
    return [];
  }
}

if (check) {
  const problems: string[] = [];
  for (const [name, bytes] of outputs) {
    let current: Uint8Array | undefined;
    try {
      current = await readFile(join(dist, name));
    } catch {
      problems.push(`${name} is missing`);
      continue;
    }
    if (Buffer.compare(Buffer.from(current), Buffer.from(bytes)) !== 0) {
      problems.push(`${name} is stale`);
    }
  }
  for (const name of await existing()) {
    if (!outputs.has(name)) {
      problems.push(`${name} isn't a build output`);
    }
  }
  if (problems.length > 0) {
    console.error(
      `runtime/browser/dist doesn't match src/ (${problems.join("; ")}): run \`bun run build\` and commit dist/`,
    );
    process.exit(1);
  }
  console.log(`dist/ is up to date: ${total} bytes (${sizes})`);
} else {
  await mkdir(dist, { recursive: true });
  for (const name of await existing()) {
    if (!outputs.has(name)) {
      await rm(join(dist, name), { recursive: true });
    }
  }
  for (const [name, bytes] of outputs) {
    await writeFile(join(dist, name), bytes);
  }
  console.log(`wrote dist/: ${total} bytes (${sizes})`);
}
