[workspace]
resolver = "3"
members = [
    "agent_control",
    "asset_pack",
    "compiler",
    "runtime",
    "material_graph",
    "mesh_tooling",
    "texture_tooling",
    "client",
]

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
panic = "abort"

[profile.dev]
debug = 0
split-debuginfo = "off"
incremental = false

[profile.test]
debug = 0
split-debuginfo = "off"
incremental = false
