// Snow, glacier blue, pine shadow and lantern gold; the valley remains the main surface.
export const winterStyle = `
.winter-game{position:fixed;inset:0;pointer-events:none;color:#eef5ef;font:14px 'Avenir Next','Trebuchet MS',sans-serif;text-shadow:0 1px 5px #122d3b;z-index:5}
.winter-game[hidden],.winter-panel[hidden]{display:none}
.winter-top{position:absolute;left:34px;right:34px;top:28px;display:flex;justify-content:space-between;gap:24px}
.winter-top h1{margin:0;font:normal clamp(25px,3vw,36px) Georgia,'Times New Roman',serif;letter-spacing:-.04em}
.winter-top p{margin:8px 0 0;font-size:13px;line-height:1.5}
.winter-weather{display:flex;gap:10px;align-items:center;align-self:flex-start;background:#183843b8;padding:9px 12px;border-radius:5px}
.winter-weather label{font-size:12px}.winter-weather meter{width:96px;height:10px;accent-color:#f4bd6b}.winter-weather meter::-webkit-meter-bar{background:#44636a;border:0}.winter-weather meter::-webkit-meter-optimum-value{background:#f4bd6b}.winter-weather meter::-webkit-meter-suboptimum-value{background:#e99860}
.winter-game button{pointer-events:auto;text-shadow:none;color:#edf4ed;background:#254d5ddd;border:1px solid #93bdc481;font-size:13px;border-radius:5px;padding:10px 14px;min-height:40px;cursor:pointer;font-family:inherit}
.winter-game button:hover{background:#396579}.winter-game button:focus-visible{outline:3px solid #f4bd6b;outline-offset:3px}
.winter-route{position:absolute;left:35px;top:125px;display:flex;flex-direction:column;gap:9px;padding:12px 16px 12px 0;font-size:12px;color:#deedf0}
.winter-route .restored{color:#ffd18b}
.winter-map{position:absolute;bottom:68px;right:32px;width:154px;height:170px;background:#163846b8;border-radius:55% 55% 18px 18px;overflow:visible;padding:15px;filter:drop-shadow(0 3px 10px #122c3244)}
.winter-help{position:absolute;bottom:24px;left:34px;right:220px;font-size:11px;line-height:1.8}.winter-help span{margin-left:16px}
.winter-prompt{position:absolute;bottom:83px;left:50%;transform:translateX(-50%);padding:11px 20px;border-radius:30px;background:#1d4253de;text-align:center;max-width:70%;font-size:13px;line-height:1.5}
.winter-notice{position:absolute;top:31%;left:50%;transform:translateX(-50%);text-align:center;max-width:420px;font:20px/1.4 Georgia,serif;color:#fff1d5}
.winter-panel{pointer-events:auto;position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);width:min(520px,calc(100vw - 40px));max-height:calc(100dvh - 40px);overflow:auto;background:#e7f2ed;color:#20414d;padding:36px 38px;border-radius:18px 18px 48px 18px;text-shadow:none;box-shadow:0 0 0 100vmax #12303d88,0 18px 80px #142b3e66}
.winter-panel h2{font:normal clamp(29px,4vw,39px)/1.12 Georgia,serif;letter-spacing:-.035em;margin:0 0 20px;max-width:390px}
.winter-panel p{font-size:14px;line-height:1.8;color:#365965;margin:0 0 25px;max-width:390px}
.graphics-control{font-size:11px;white-space:nowrap}.graphics-control select{margin-left:4px}.winter-graphics{display:flex;align-items:center;justify-content:space-between;gap:18px;margin:0 0 20px;font-size:13px}.winter-graphics select{background:#d4e4dd;color:#20414d;border:1px solid #93b6b8;text-shadow:none;font-family:inherit;min-height:42px;max-width:220px}.winter-graphics select:focus-visible{outline:3px solid #245568;outline-offset:3px}.winter-panel-actions{display:flex;flex-wrap:wrap;gap:9px}.winter-panel-actions button{background:transparent;color:#20414d;border-color:#93b6b8;padding:10px 13px;font-size:12px}.winter-panel-actions button:hover{background:#cfdfd9}.winter-panel-actions button.winter-primary{background:#245568;border-color:#245568;color:#f7faf3;width:100%;font-size:15px;padding:14px;margin-bottom:5px}.winter-panel-actions button.winter-primary:hover{background:#326b7e}
.winter-touch{display:none}.game-launch{background:#d8e9e0!important;color:#21495a!important;font-weight:600!important;border-color:#d8e9e0!important}
@media(pointer:coarse){.winter-touch{display:flex;position:absolute;bottom:27px;left:24px;right:24px;justify-content:space-between;align-items:center;pointer-events:none}.winter-stick{width:115px;height:115px;border-radius:50%;background:#214452aa;border:1px solid #e6f7ef77;pointer-events:auto;touch-action:none;display:grid;place-items:center}.winter-stick span{display:block;width:55px;height:55px;border-radius:50%;background:#d6e8e194;border:1px solid #eef7edbb}.winter-action{width:83px;height:83px;border-radius:50%!important;touch-action:none}.winter-help{display:none}.winter-map{bottom:155px}.winter-prompt{bottom:158px;font-size:12px}}
@media(max-width:600px){.winter-top{left:18px;right:18px;top:18px;gap:12px}.winter-weather{flex-wrap:wrap;width:105px;gap:5px;padding:8px}.winter-weather button{padding:6px 10px;min-height:32px}.winter-weather meter{width:68px}.winter-top p{font-size:12px;max-width:200px}.winter-route{left:18px;top:121px;font-size:11px;gap:7px}.winter-map{width:112px;height:133px;right:17px;padding:9px}.winter-notice{top:40%;font-size:17px;max-width:78%;width:290px}.winter-panel{padding:28px 25px}.winter-help{left:18px;right:155px;bottom:16px}.winter-help span{display:block;margin-left:0}.winter-prompt{max-width:80%;width:max-content}.winter-route{background:#15374666;border-radius:0 12px 12px 0;padding:10px}.winter-weather label{font-size:10px}}
@media(prefers-reduced-motion:reduce){.winter-game *{scroll-behavior:auto}}
`;
