#!/usr/bin/env python3
"""Generate pinned identifier properties; does not fetch or use host Unicode data."""
from pathlib import Path
import hashlib
root = Path(__file__).resolve().parents[1]
data = (root / 'unicode/DerivedCoreProperties-16.0.0.txt').read_bytes()
assert data.startswith(b'# DerivedCoreProperties-16.0.0.txt')
assert hashlib.sha256(data).hexdigest() == '39d35161f2954497f69e08bdb9e701493f476a3d30222de20028feda36c1dabd', 'pinned Unicode 16 data changed'
properties = {p: [] for p in ('XID_Start', 'XID_Continue', 'Default_Ignorable_Code_Point')}
for line in data.decode().splitlines():
    text = line.split('#')[0].strip()
    if not text: continue
    span, prop, *_ = [x.strip() for x in text.split(';')]
    if prop not in properties: continue
    ends = span.split('..')
    properties[prop].append((int(ends[0],16), int(ends[-1],16)))
out = ['// Generated by tools/generate_unicode.py. Do not edit.', '// Unicode 16.0.0; DerivedCoreProperties SHA256: '+hashlib.sha256(data).hexdigest()]
for prop in ('Default_Ignorable_Code_Point',):
    spans = properties[prop]
    out.append('#[rustfmt::skip]')
    out.append('pub const '+prop.upper()+': &[(u32,u32)] = &[')
    out.extend(f'    (0x{a:X}, 0x{b:X}),' for a,b in spans)
    out.append('];')
out.append('#[rustfmt::skip]')
out.append('pub fn contains(table: &[(u32,u32)], c: char) -> bool { let n = c as u32; table.binary_search_by(|&(a,b)| if n<a { std::cmp::Ordering::Greater } else if n>b { std::cmp::Ordering::Less } else { std::cmp::Ordering::Equal }).is_ok() }')
(root / 'src/unicode16.rs').write_text('\n'.join(out)+'\n')

# Logos needs literal regex classes. Keep the lexical productions in lexical.rs;
# this generated invocation supplies only pinned property data. The subtraction
# classes enforce the existing default-ignorable exclusion declaratively.
def regex_class(spans, underscore=False):
    return '[' + ('_' if underscore else '') + ''.join(
        rf'\u{{{a:X}}}' + (rf'-\u{{{b:X}}}' if a != b else '')
        for a, b in spans) + ']'

start = regex_class(properties['XID_Start'], underscore=True)
continuation = regex_class(properties['XID_Continue'], underscore=True)
ignorable = regex_class(properties['Default_Ignorable_Code_Point'])
lexical = [
    '// Generated by tools/generate_unicode.py. Do not edit.',
    '// Unicode 16.0.0; DerivedCoreProperties SHA256: ' + hashlib.sha256(data).hexdigest(),
    'lexical_rules!(',
]
for expression in (start, continuation, ignorable,
                   '[' + start + '--' + ignorable + ']',
                   '[' + continuation + '--' + ignorable + ']'):
    lexical.append('    r"' + expression + '",')
lexical.append(');')
(root / 'src/lexical_unicode.rs').write_text('\n'.join(lexical) + '\n')
