type Matrix3 = readonly [number, number, number, number, number, number, number, number, number];

/** Coordinates entering an arbitrary downstream procedural density program:
 * q = world * worldScale + wind * time * windScale + offset.
 * Downstream warps/thresholds preserve this coordinate covariance. */
export interface AdvectedCloudDomain {
  worldScale: readonly [number, number, number];
  windScale: readonly [number, number, number];
}

export const CLOUD_DOMAIN: AdvectedCloudDomain = {
  worldScale: [0.00062, 0.00062, 0.00062],
  windScale: [-0.00062, 0, -0.00062],
};

/** Solve D_world * motion + D_wind * delta(wind*time) = 0.
 * The compiler must reject singular coordinates; guessing a motion in their
 * nullspace would not certify the downstream density program's correspondence. */
export function compileCloudAdvection(domain: AdvectedCloudDomain) {
  if (
    ![...domain.worldScale, ...domain.windScale].every(Number.isFinite) ||
    domain.worldScale.some((v) => Math.abs(v) < 1e-12)
  )
    throw new RangeError("Cloud advection requires finite, invertible domain scales");
  const motion = domain.worldScale.map((v, i) => -domain.windScale[i] / v);
  const vector = (v: readonly number[]) =>
    `vec3f(${v.map((x) => (Number.isInteger(x) ? `${x}.0` : String(x))).join(",")})`;
  return {
    motion,
    source: `// Generated by tools/compile-cloud-transport.ts. Do not edit.
const COMPILED_CLOUD_WORLD_SCALE:vec3f=${vector(domain.worldScale)};
const COMPILED_CLOUD_WIND_SCALE:vec3f=${vector(domain.windScale)};
fn compiledCloudCoordinates(world:vec3f,windTime:vec3f)->vec3f {
  return world*COMPILED_CLOUD_WORLD_SCALE+windTime*COMPILED_CLOUD_WIND_SCALE;
}
fn compiledCloudMotion(previousWindTime:vec3f,currentWindTime:vec3f)->vec3f {
  return (currentWindTime-previousWindTime)*${vector(motion)};
}
// Integral on [0,1] of clamp(a+(b-a)*s,0,1), including support crossings.
fn compiledCloudDensityIntegral(a:f32,b:f32)->f32 {
  let low=min(a,b);let high=max(a,b);let delta=high-low;
  if(high<=0.0) {return 0.0;}
  if(low>=1.0) {return 1.0;}
  if(delta<0.00001) {return clamp(0.5*(a+b),0.0,1.0);}
  let start=clamp(-low/delta,0.0,1.0);
  let end=clamp((1.0-low)/delta,0.0,1.0);
  return 0.5*(clamp(low,0.0,1.0)+clamp(high,0.0,1.0))*(end-start)+1.0-end;
}
// A projected line is fractional-linear in depth. Its derivative has constant
// sign while the denominator stays positive, so endpoints enclose its image.
fn compiledCloudProjectionRadius(nearPoint:vec3f,meanPoint:vec3f,farPoint:vec3f,
  right:vec3f,up:vec3f,forward:vec3f,scale:vec2f)->f32 {
  let z=vec3f(dot(nearPoint,forward),dot(meanPoint,forward),dot(farPoint,forward));
  if(any(z<=vec3f(0.001))) {return 1e10;}
  let a=vec2f(dot(nearPoint,right),dot(nearPoint,up))/z.x*scale;
  let b=vec2f(dot(meanPoint,right),dot(meanPoint,up))/z.y*scale;
  let c=vec2f(dot(farPoint,right),dot(farPoint,up))/z.z*scale;
  return max(length(a-b),length(c-b));
}
`,
  };
}

/** CPU reference for the fractional-linear interval, used to audit the emitted
 * endpoint rule independently of the renderer's history heuristics. */
export function projectCloudDepthInterval(
  origin: readonly [number, number, number],
  direction: readonly [number, number, number],
  depths: readonly [number, number],
  basis: Matrix3,
) {
  if (
    ![...origin, ...direction, ...depths, ...basis].every(Number.isFinite) ||
    depths[0] < 0 ||
    depths[1] < depths[0]
  )
    throw new RangeError("Invalid cloud projection interval");
  const project = (t: number) => {
    const p = origin.map((v, i) => v + direction[i] * t);
    const dot = (offset: number) =>
      p[0] * basis[offset] + p[1] * basis[offset + 1] + p[2] * basis[offset + 2];
    const z = dot(6);
    return z > 0 ? [dot(0) / z, dot(3) / z] : null;
  };
  const a = project(depths[0]),
    b = project(depths[1]);
  return a && b ? { min: a.map((v, i) => Math.min(v, b[i])), max: a.map((v, i) => Math.max(v, b[i])) } : null;
}
