//! Building: lowering to IR, the back ends, and the build's files (vision.md, "What ships and
//! how it runs"): `game.wasm`, one WGSL module per pipeline, `manifest.json`, and the standard
//! browser runtime, pinned to this compiler's version (D-100).

use crate::query::{Db, Query};
use crate::{CheckPackage, Shared};
use std::rc::Rc;
use wrela_diag::{Diagnostic, FileId, Span, codes};
use wrela_lower::{Lowered, PipelineKind, Roots};

/// The standard browser runtime, embedded in the compiler so every build ships the version the
/// compiler was built with. Generated by `bun run build` in runtime/browser.
pub const RUNTIME_FILES: &[(&str, &[u8])] = &[
    ("index.html", include_bytes!("../../../runtime/browser/dist/index.html")),
    ("main.js", include_bytes!("../../../runtime/browser/dist/main.js")),
    ("worker.js", include_bytes!("../../../runtime/browser/dist/worker.js")),
];

#[derive(Debug)]
pub struct LowerOutput {
    pub lowered: Option<Lowered>,
    pub diagnostics: Vec<Diagnostic>,
}

/// Query: the package lowered to IR (and the per-instantiation effect checks that come with
/// it). Empty when checking found errors.
pub struct LowerPackage;
impl Query for LowerPackage {
    type Key = ();
    type Value = Shared<LowerOutput>;
    const NAME: &'static str = "lower_package";
    fn compute(db: &Db, _: &()) -> Self::Value {
        let check = db.get::<CheckPackage>(&());
        let Some(checked) = check.checked.as_ref().filter(|_| !check.has_errors()) else {
            return Shared(Rc::new(LowerOutput { lowered: None, diagnostics: Vec::new() }));
        };
        let roots = Roots::of(checked);
        let (lowered, diagnostics) = wrela_lower::lower(checked, &roots);
        let ok = !diagnostics.iter().any(|d| d.is_error());
        Shared(Rc::new(LowerOutput { lowered: ok.then_some(lowered), diagnostics }))
    }
}

#[derive(Debug)]
pub struct BuildOutput {
    /// Each file of the build, by its path relative to the output directory, in a fixed order.
    pub files: Vec<(String, Vec<u8>)>,
    pub diagnostics: Vec<Diagnostic>,
}

/// Query: the build's files.
pub struct BuildPackage;
impl Query for BuildPackage {
    type Key = ();
    type Value = Shared<BuildOutput>;
    const NAME: &'static str = "build_package";
    fn compute(db: &Db, _: &()) -> Self::Value {
        let lowered = db.get::<LowerPackage>(&());
        let Some(l) = lowered.lowered.as_ref() else {
            return Shared(Rc::new(BuildOutput { files: Vec::new(), diagnostics: Vec::new() }));
        };
        Shared(Rc::new(emit(l)))
    }
}

fn internal(message: String) -> Diagnostic {
    Diagnostic::new(codes::E0702, Span::new(FileId(0), 0, 0), message)
}

fn emit(l: &Lowered) -> BuildOutput {
    let mut diagnostics = Vec::new();
    let mut files = Vec::new();
    match wrela_wasm::emit(&l.cpu) {
        Ok(bytes) => {
            if let Err(e) = wrela_wasm::check_no_relaxed_simd(&bytes) {
                diagnostics.push(internal(format!("internal: {e}")));
            }
            files.push(("game.wasm".to_string(), bytes));
        }
        Err(e) => diagnostics.push(internal(format!("internal: the WASM back end failed: {e}"))),
    }
    let mut manifest = wrela_abi::Manifest::new("game.wasm");
    for (i, p) in l.pipelines.iter().enumerate() {
        let shader = format!("pipeline_{i}.wgsl");
        match wrela_wgsl::emit(&p.module) {
            Ok(text) => files.push((shader.clone(), text.into_bytes())),
            Err(e) => diagnostics.push(internal(format!(
                "internal: the WGSL back end failed for `{}`: {e}",
                p.name
            ))),
        }
        let stage = match &p.kind {
            PipelineKind::Compute { entry, workgroup_size } => {
                wrela_abi::manifest::Stage::Compute {
                    entry: entry.clone(),
                    workgroup_size: *workgroup_size,
                }
            }
            PipelineKind::Render { vertex_entry, fragment_entry } => {
                wrela_abi::manifest::Stage::Render {
                    vertex_entry: vertex_entry.clone(),
                    fragment_entry: fragment_entry.clone(),
                }
            }
        };
        manifest.pipelines.push(wrela_abi::manifest::Pipeline {
            name: p.name.clone(),
            shader,
            stage,
            uniform: p.uniform.as_ref().map(|u| wrela_abi::manifest::UniformBlock {
                binding: u.binding,
                size: u.size,
                space: if u.storage {
                    wrela_abi::manifest::UniformSpace::Storage
                } else {
                    wrela_abi::manifest::UniformSpace::Uniform
                },
            }),
            buffers: p
                .buffers
                .iter()
                .map(|&(binding, rw)| wrela_abi::manifest::BufferBinding {
                    binding,
                    access: if rw {
                        wrela_abi::manifest::Access::ReadWrite
                    } else {
                        wrela_abi::manifest::Access::Read
                    },
                })
                .collect(),
        });
    }
    if let Err(e) = manifest.validate() {
        diagnostics.push(internal(format!("internal: {e}")));
    }
    files.push(("manifest.json".to_string(), manifest.to_json().into_bytes()));
    for (path, bytes) in RUNTIME_FILES {
        files.push((path.to_string(), bytes.to_vec()));
    }
    BuildOutput { files, diagnostics }
}
