//! Building: the back ends, and the build's files (vision.md, "What ships and how it runs"):
//! `game.wasm`, one WGSL module per pipeline, `manifest.json`, and the standard browser
//! runtime, pinned to this compiler's version (D-100).

use wrela_diag::{Diagnostic, SourceMap};
use wrela_lower::{Lowered, PipelineKind};

/// The standard browser runtime, embedded in the compiler so every build ships the version the
/// compiler was built with. Generated by `bun run build` in runtime/browser.
pub const RUNTIME_FILES: &[(&str, &[u8])] = &[
    ("index.html", include_bytes!("../../../runtime/browser/dist/index.html")),
    ("main.js", include_bytes!("../../../runtime/browser/dist/main.js")),
    ("worker.js", include_bytes!("../../../runtime/browser/dist/worker.js")),
    ("worklet.js", include_bytes!("../../../runtime/browser/dist/worklet.js")),
];

#[derive(Debug)]
pub struct BuildOutput {
    /// Each file of the build, by its path relative to the output directory, in a fixed order.
    pub files: Vec<(String, Vec<u8>)>,
    pub diagnostics: Vec<Diagnostic>,
    /// Where each WASM offset is in the source: for a frame test's failure (`frames`).
    pub lines: Vec<(u32, Option<wrela_diag::Span>)>,
}

/// Runs the back ends over a lowered program. `sources` names the locations a trap reports.
pub fn emit(l: &Lowered, sources: &SourceMap, simd: bool) -> BuildOutput {
    let mut diagnostics = Vec::new();
    let mut files = Vec::new();
    let mut code_lines = Vec::new();
    let options = wrela_wasm::Options { simd, ..wrela_wasm::Options::default() };
    match wrela_wasm::emit_with(&l.cpu, options) {
        Ok(out) => {
            code_lines = out.lines.clone();
            // Where each part of the code came from, as `file:line:column`, for trap messages.
            let entries: Vec<(u32, Option<String>)> = out
                .lines
                .iter()
                .map(|&(offset, span)| {
                    (offset, span.map(|s| sources.file(s.file).location(s.start)))
                })
                .collect();
            let lines = wrela_abi::lines::Lines::new(entries).encode();
            let wasm = wrela_wasm::with_custom_section(out.wasm, wrela_abi::lines::SECTION, &lines);
            files.push(("game.wasm".to_string(), wasm));
        }
        Err(e) => diagnostics.push(Diagnostic::internal(format!("the WASM back end failed: {e}"))),
    }
    let mut manifest = wrela_abi::Manifest::new("game.wasm");
    for (i, p) in l.pipelines.iter().enumerate() {
        let shader = format!("pipeline_{i}.wgsl");
        let wgsl = match wrela_wgsl::emit(&p.module) {
            Ok(w) => w,
            Err(e) => {
                diagnostics.push(Diagnostic::internal(format!(
                    "the WGSL back end failed for `{}`: {e}",
                    p.name
                )));
                continue;
            }
        };
        // The entry points by the names the shader has (the WGSL writer may rename them).
        let stage = match (&p.kind, wgsl.entry_points.as_slice()) {
            (PipelineKind::Compute { workgroup_size }, [entry]) => {
                wrela_abi::manifest::Stage::Compute {
                    entry: entry.clone(),
                    workgroup_size: *workgroup_size,
                }
            }
            (PipelineKind::Render, [vertex, fragment]) => wrela_abi::manifest::Stage::Render {
                vertex_entry: vertex.clone(),
                fragment_entry: fragment.clone(),
                blend: p.blend,
            },
            _ => {
                diagnostics.push(Diagnostic::internal(format!(
                    "the shader for `{}` has the wrong entry points",
                    p.name
                )));
                continue;
            }
        };
        files.push((shader.clone(), wgsl.text.into_bytes()));
        manifest.pipelines.push(wrela_abi::manifest::Pipeline {
            name: p.name.clone(),
            shader,
            stage,
            uniform: p.uniform.as_ref().map(|u| wrela_abi::manifest::UniformBlock {
                binding: u.binding,
                size: u.size,
                space: if u.storage {
                    wrela_abi::manifest::UniformSpace::Storage
                } else {
                    wrela_abi::manifest::UniformSpace::Uniform
                },
            }),
            bindings: p.bindings.clone(),
            debug_flag: p.debug_flag,
        });
    }
    if let Err(e) = manifest.validate() {
        diagnostics.push(Diagnostic::internal(e.to_string()));
    }
    files.push(("manifest.json".to_string(), manifest.to_json().into_bytes()));
    for (path, bytes) in RUNTIME_FILES {
        files.push((path.to_string(), bytes.to_vec()));
    }
    BuildOutput { files, diagnostics, lines: code_lines }
}
