import type {
  CharacterDefinition,
  Document,
  FieldNode,
  Project,
  RecipeDefinition,
  RecipeInstance,
} from "./documents";
import type { Vec3 } from "./math";
import { instantiateRecipes } from "./recipes";

const base = (id: string, name: string) => ({ id, name, schemaVersion: 1 as const, dependencies: [] });
/** A reusable content family, kept separate from the reference rendering scene
 * so fixture changes do not silently change visual benchmark composition. */
export function coniferFamilyFixture() {
  const recipe: RecipeDefinition = {
    id: "alpine-conifer-family",
    version: "1",
    template: {
      ...base("conifer-template", "Conifer template"),
      kind: "vegetation",
      seed: 37,
      height: 7,
      radius: 2,
      branches: 9,
      material: "pine-needles",
      trunkMaterial: "bark",
      windResponse: 0.35,
      variation: 0.4,
    },
    parameters: {
      stature: { default: 7, min: 0.5, max: 20 },
      crown: { default: 2, min: 0.1, max: 6 },
      seed: { default: 37, min: 0, max: 100000, integer: true },
    },
    bindings: [
      { parameter: "stature", path: ["height"] },
      { parameter: "crown", path: ["radius"] },
      { parameter: "seed", path: ["seed"] },
    ],
  };
  const recipeInstances: RecipeInstance[] = [
    { id: "family-pine-mature", name: "Mature alpine pine", recipe: recipe.id, version: "1" },
    {
      id: "family-pine-young",
      name: "Young alpine pine",
      recipe: recipe.id,
      version: "1",
      parameters: { stature: 3, crown: 0.8, seed: 71 },
    },
    {
      id: "family-pine-exposed",
      name: "Exposed alpine pine",
      recipe: recipe.id,
      version: "1",
      parameters: { stature: 5, crown: 1.6, seed: 103 },
      overrides: [{ path: ["windResponse"], value: 0.8 }],
    },
  ];
  return { recipes: [recipe], recipeInstances, documents: instantiateRecipes([recipe], recipeInstances) };
}
export function shape(
  id: string,
  name: string,
  position: Vec3,
  size: Vec3,
  kind: FieldNode["kind"] = "ellipsoid",
): FieldNode {
  return { id, name, kind, position, size, rotation: [0, 0, 0], radius: 0.3, blend: 0.16, children: [] };
}
export function referenceProject(): Project {
  const bunnyNodes: FieldNode[] = [
    shape("body", "Body", [0, 0.9, 0], [0.52, 0.68, 0.43]),
    shape("head", "Head", [0, 1.68, 0.12], [0.4, 0.4, 0.37]),
    shape("left-ear", "Left ear", [-0.22, 2.3, 0.04], [0.12, 0.55, 0.12]),
    shape("right-ear", "Right ear", [0.22, 2.3, 0.04], [0.12, 0.55, 0.12]),
    shape("left-foot", "Left foot", [-0.3, 0.22, 0.18], [0.23, 0.2, 0.43]),
    shape("right-foot", "Right foot", [0.3, 0.22, 0.18], [0.23, 0.2, 0.43]),
    shape("tail", "Tail", [0, 0.63, -0.46], [0.24, 0.24, 0.24]),
    shape("left-arm", "Left arm", [-0.42, 0.95, 0.2], [0.17, 0.34, 0.18]),
    shape("right-arm", "Right arm", [0.42, 0.95, 0.2], [0.17, 0.34, 0.18]),
  ];
  const featureNodes: FieldNode[] = [
    { ...shape("left-eye", "Left eye", [-0.19, 1.79, 0.435], [0.072, 0.09, 0.055]), material: "onyx-eyes" },
    { ...shape("right-eye", "Right eye", [0.19, 1.79, 0.435], [0.072, 0.09, 0.055]), material: "onyx-eyes" },
    { ...shape("nose", "Nose", [0, 1.66, 0.505], [0.068, 0.047, 0.053]), material: "rose-nose" },
    {
      ...shape("left-inner-ear", "Left inner ear", [-0.22, 2.31, 0.144], [0.064, 0.405, 0.04]),
      material: "rose-ears",
    },
    {
      ...shape("right-inner-ear", "Right inner ear", [0.22, 2.31, 0.144], [0.064, 0.405, 0.04]),
      material: "rose-ears",
    },
    shape("left-muzzle", "Left muzzle", [-0.085, 1.58, 0.424], [0.115, 0.095, 0.085]),
    shape("right-muzzle", "Right muzzle", [0.085, 1.58, 0.424], [0.115, 0.095, 0.085]),
  ];
  const root = {
    ...shape("anatomy", "Anatomy", [0, 0, 0], [1, 1, 1], "smoothUnion"),
    children: bunnyNodes.map((n) => n.id),
    blend: 0.12,
  };
  const bunny: CharacterDefinition = {
    ...base("polar-bunny", "Polar bunny"),
    kind: "character",
    material: "snow-fur",
    field: {
      root: "creature",
      nodes: [
        {
          ...shape("creature", "Creature", [0, 0, 0], [1, 1, 1], "union"),
          children: ["anatomy", ...featureNodes.map((node) => node.id)],
        },
        root,
        ...bunnyNodes,
        ...featureNodes,
      ],
      bounds: { min: [-0.9, -0.1, -0.9], max: [0.9, 3, 0.9] },
      resolution: 40,
    },
    joints: [
      {
        id: "root",
        name: "Root",
        parent: null,
        position: [0, 0.3, 0],
        rotation: [0, 0, 0],
        radius: 1,
        minimum: -1,
        maximum: 1,
      },
      {
        id: "head-joint",
        name: "Head",
        parent: "root",
        position: [0, 1.65, 0.1],
        rotation: [0, 0, 0],
        radius: 0.65,
        minimum: -0.6,
        maximum: 0.6,
      },
      {
        id: "ear-l",
        name: "Left ear",
        parent: "head-joint",
        position: [-0.22, 2.05, 0.04],
        rotation: [0, 0, 0],
        radius: 0.45,
        minimum: -0.7,
        maximum: 0.7,
      },
      {
        id: "ear-r",
        name: "Right ear",
        parent: "head-joint",
        position: [0.22, 2.05, 0.04],
        rotation: [0, 0, 0],
        radius: 0.45,
        minimum: -0.7,
        maximum: 0.7,
      },
    ],
    motions: [
      {
        id: "idle",
        name: "Quiet breath",
        duration: 3,
        loop: true,
        keys: [
          { joint: "root", time: 0, rotation: [0, 0, 0], translation: [0, 0, 0] },
          { joint: "root", time: 1.5, rotation: [0.025, 0, 0], translation: [0, 0.045, 0] },
          { joint: "root", time: 3, rotation: [0, 0, 0], translation: [0, 0, 0] },
          { joint: "ear-l", time: 0, rotation: [0, 0, -0.1], translation: [0, 0, 0] },
          { joint: "ear-l", time: 1.5, rotation: [0.1, 0, 0.1], translation: [0, 0, 0] },
          { joint: "ear-l", time: 3, rotation: [0, 0, -0.1], translation: [0, 0, 0] },
        ],
      },
      {
        id: "hop",
        name: "Snow hop",
        duration: 1.2,
        loop: true,
        keys: [
          { joint: "root", time: 0, rotation: [0, 0, 0], translation: [0, 0, 0] },
          { joint: "root", time: 0.3, rotation: [-0.2, 0, 0], translation: [0, 0.7, 0.2] },
          { joint: "root", time: 0.6, rotation: [0.15, 0, 0], translation: [0, 0, 0.45] },
          { joint: "root", time: 1.2, rotation: [0, 0, 0], translation: [0, 0, 0] },
        ],
      },
    ],
    physics: { mode: "kinematic", mass: 2, restitution: 0.15, friction: 0.7 },
  };
  const documents: Document[] = [
    {
      ...base("snow-fur", "Porcelain snow"),
      kind: "material",
      color: [0.88, 0.92, 0.92],
      secondary: [0.65, 0.74, 0.78],
      roughness: 0.83,
      metallic: 0,
      pattern: "noise",
      scale: 18,
      normalStrength: 0.12,
    },
    {
      ...base("onyx-eyes", "Onyx eyes"),
      kind: "material",
      color: [0.009, 0.016, 0.022],
      secondary: [0.025, 0.035, 0.04],
      roughness: 0.16,
      metallic: 0,
      pattern: "solid",
      scale: 1,
      normalStrength: 0,
    },
    {
      ...base("rose-nose", "Rose nose"),
      kind: "material",
      color: [0.38, 0.15, 0.18],
      secondary: [0.42, 0.2, 0.23],
      roughness: 0.42,
      metallic: 0,
      pattern: "solid",
      scale: 1,
      normalStrength: 0,
    },
    {
      ...base("rose-ears", "Warm inner ears"),
      kind: "material",
      color: [0.7, 0.38, 0.4],
      secondary: [0.82, 0.5, 0.52],
      roughness: 0.86,
      metallic: 0,
      pattern: "noise",
      scale: 14,
      normalStrength: 0.04,
    },
    {
      ...base("pine-needles", "Alpine needles"),
      kind: "material",
      color: [0.1, 0.23, 0.2],
      secondary: [0.32, 0.46, 0.39],
      roughness: 0.9,
      metallic: 0,
      pattern: "noise",
      scale: 4,
      normalStrength: 0.2,
    },
    {
      ...base("bark", "Silver bark"),
      kind: "material",
      color: [0.21, 0.15, 0.12],
      secondary: [0.45, 0.34, 0.24],
      roughness: 0.95,
      metallic: 0,
      pattern: "stripes",
      scale: 6,
      normalStrength: 0.2,
    },
    {
      ...base("stone", "Glacial stone"),
      kind: "material",
      color: [0.39, 0.5, 0.54],
      secondary: [0.79, 0.85, 0.85],
      roughness: 0.8,
      metallic: 0.05,
      pattern: "marble",
      scale: 3,
      normalStrength: 0.2,
    },
    {
      ...base("ground", "Alpine ground"),
      kind: "material",
      color: [0.6, 0.72, 0.71],
      secondary: [0.9, 0.94, 0.93],
      roughness: 0.95,
      metallic: 0,
      pattern: "noise",
      scale: 0.4,
      normalStrength: 0.16,
    },
    bunny,
    {
      ...base("river-stone", "River stone"),
      kind: "object",
      material: "stone",
      collision: "sphere",
      field: {
        root: "stone-root",
        nodes: [{ ...shape("stone-root", "Stone", [0, 0.8, 0], [1.2, 0.8, 0.9]), rotation: [0, 0.25, 0.18] }],
        bounds: { min: [-1.6, -0.3, -1.5], max: [1.6, 2, 1.5] },
        resolution: 32,
      },
    },
    {
      ...base("alpine-pine", "Alpine pine"),
      kind: "vegetation",
      seed: 37,
      height: 7,
      radius: 2,
      branches: 9,
      material: "pine-needles",
      trunkMaterial: "bark",
      windResponse: 0.35,
      variation: 0.4,
    },
    {
      ...base("winter-sky", "Winter afternoon"),
      kind: "environment",
      model: "analytic-sky",
      sunElevation: 0.48,
      sunAzimuth: -0.8,
      turbidity: 3,
      fogDensity: 0.007,
      skyColor: [0.23, 0.43, 0.58],
      horizonColor: [0.85, 0.8, 0.72],
      groundColor: [0.18, 0.25, 0.27],
      wind: [1.5, 0, 0.4],
    },
    {
      ...base("daylight", "Soft daylight"),
      kind: "lighting",
      ambient: 0.6,
      lights: [
        { id: "sun", type: "directional", position: [-3, 6, 4], color: [1, 0.88, 0.72], intensity: 3 },
      ],
    },
    {
      ...base("coastal-waves", "Glacial water"),
      kind: "water",
      level: -1.3,
      color: [0.08, 0.34, 0.39],
      roughness: 0.15,
      waves: [
        { amplitude: 0.12, wavelength: 8, speed: 1.2, direction: 0.4, phase: 0 },
        { amplitude: 0.06, wavelength: 3.2, speed: 0.8, direction: 1.7, phase: 1 },
      ],
    },
    {
      ...base("valley-terrain", "Winter valley terrain"),
      kind: "terrain",
      seed: 82,
      amplitude: 11,
      frequency: 0.016,
      octaves: 4,
      baseHeight: 0,
      material: "ground",
      interventions: [
        { id: "home-clearing", kind: "flatten", center: [0, 0], radius: 12, strength: 1, targetHeight: 0 },
        { id: "river-valley", kind: "valley", center: [30, 10], radius: 23, strength: 7, targetHeight: -3 },
      ],
    },
    {
      ...base("winter-valley", "Winter valley"),
      kind: "world",
      generatorVersion: "wrela-world-1",
      terrain: "valley-terrain",
      environment: "winter-sky",
      lighting: "daylight",
      water: "coastal-waves",
      populations: [
        {
          id: "conifer-line",
          definition: "alpine-pine",
          spacing: 11,
          density: 0.58,
          minHeight: -0.4,
          maxHeight: 40,
          maxSlope: 0.8,
          seed: 42,
        },
      ],
      instances: [
        {
          id: "bunny-instance",
          definition: "polar-bunny",
          position: [0, 0, 0],
          rotation: [0, 0, 0],
          scale: 1,
        },
        {
          id: "stone-instance",
          definition: "river-stone",
          position: [3, 0, 1],
          rotation: [0, 0.4, 0],
          scale: 1.2,
        },
      ],
    },
    {
      ...base("neutral-stage", "Neutral studio"),
      kind: "stage",
      environment: "winter-sky",
      lighting: "daylight",
      ground: true,
      exposure: 1,
      camera: { position: [5, 3.2, 7], target: [0, 1.2, 0], fov: 42 },
      subjects: ["polar-bunny"],
    },
  ];
  return { schemaVersion: 1, id: "winter-garden", name: "Winter garden", entry: "winter-valley", documents };
}
