// The ABI's test vectors (runtime/abi/vectors.json, generated by the wrela-abi crate from its
// own encoders and decoders): this runtime must make the same of each, down to the messages.

import { describe, expect, test } from "bun:test";
import { Checker, CommandError } from "../src/check.ts";
import { StateHash } from "../src/hash.ts";
import { Lines } from "../src/lines.ts";
import { parseManifest } from "../src/manifest.ts";
import { parseScript } from "../src/input.ts";
import { decode, Sequencer, StreamError } from "../src/stream.ts";
import { TickLogWriter, wasmHash } from "../src/ticks.ts";
import { type ErrorVector, vectors } from "./fixtures.ts";

const bytes = (hex: string) => Uint8Array.from(hex.match(/../g) ?? [], (b) => Number.parseInt(b, 16));

/** What a call throws, as the vectors record it. */
function thrown(f: () => unknown): ErrorVector | null {
  try {
    f();
  } catch (e) {
    expect(e).toBeInstanceOf(StreamError);
    return { kind: (e as StreamError).kind, message: (e as Error).message };
  }
  return null;
}

/** A decoded command with its byte arrays as plain arrays, as the vectors hold them. */
const plain = (c: object) =>
  Object.fromEntries(Object.entries(c).map(([k, v]) => [k, v instanceof Uint8Array ? Array.from(v) : v]));

test("state hashes", () => {
  for (const v of vectors.hashes) {
    const h = new StateHash();
    h.update(bytes(v.bytes));
    expect(h.hex()).toBe(v.hash);
  }
});

describe("batches", () => {
  for (const v of vectors.batches) {
    test(v.name, () => {
      let commands: unknown[] | undefined;
      const error = thrown(() => {
        commands = decode(bytes(v.bytes)).map(plain);
      });
      if (v.outcome.error) {
        expect(error).toEqual(v.outcome.error);
      } else {
        expect(error).toBeNull();
        expect(commands).toEqual(v.outcome.commands);
      }
    });
  }
});

describe("sequences", () => {
  for (const v of vectors.sequences) {
    test(v.name, () => {
      const s = new Sequencer();
      const error = thrown(() => {
        for (const c of decode(bytes(v.bytes))) s.step(c);
        s.endFrame();
      });
      expect(error).toEqual(v.error);
    });
  }
});

describe("checks", () => {
  const manifest = parseManifest(vectors.checks.manifest);
  for (const v of vectors.checks.batches) {
    test(v.name, () => {
      const s = new Sequencer();
      const checker = new Checker(manifest);
      let error: { opcode: string; message: string } | null = null;
      try {
        for (const c of decode(bytes(v.bytes))) {
          s.step(c);
          checker.check(c);
        }
      } catch (e) {
        expect(e).toBeInstanceOf(CommandError);
        error = { opcode: (e as CommandError).opcode, message: (e as Error).message };
      }
      expect(error).toEqual(v.error);
    });
  }
});

describe("manifests", () => {
  for (const v of vectors.manifests) {
    test(v.name, () => {
      let error: string | null = null;
      try {
        parseManifest(v.json);
      } catch (e) {
        error = (e as Error).message;
      }
      if (v.malformed) expect(error).toStartWith("invalid manifest: ");
      else expect(error).toBe(v.error);
    });
  }
});

describe("line tables", () => {
  for (const v of vectors.lines) {
    test(v.name, () => {
      let lines: Lines | null = null;
      let error: string | null = null;
      try {
        lines = Lines.decode(bytes(v.bytes));
      } catch (e) {
        error = (e as Error).message;
      }
      expect(error).toBe(v.error);
      for (const [offset, loc] of v.at) expect(lines!.at(offset)).toBe(loc);
    });
  }
});

describe("input scripts", () => {
  const hex = (b: Uint8Array) => Array.from(b, (x) => x.toString(16).padStart(2, "0")).join("");
  for (const v of vectors.input) {
    test(v.name, () => {
      if (v.error !== undefined) {
        // JSON's own errors are worded by each parser; the rest are the ABI's.
        const expected = v.error.startsWith("the script isn't JSON") ? "the script isn't JSON" : v.error;
        expect(() => parseScript(v.script)).toThrow(expected);
        return;
      }
      const events = parseScript(v.script);
      expect(events.map((e) => ("frame" in e.at ? `frame ${e.at.frame}` : `tick ${e.at.tick}`))).toEqual(v.at!);
      expect(events.map((e) => hex(e.event))).toEqual(v.events!);
    });
  }
});

describe("tick logs", () => {
  const hex = (b: Uint8Array) => Array.from(b, (x) => x.toString(16).padStart(2, "0")).join("");
  test("a build's WASM hash", () => {
    expect(wasmHash(new Uint8Array([0, 0x61, 0x73, 0x6d])).toString(16).padStart(16, "0")).toBe(vectors.tick_logs[0]!.wasm_hash);
  });
  for (const v of vectors.tick_logs) {
    test(`${v.ticks.length} ticks at ${v.hz} Hz`, () => {
      const log = new TickLogWriter(BigInt(`0x${v.wasm_hash}`), v.hz, BigInt(`0x${v.first}`));
      for (const t of v.ticks) log.push(bytes(t.records.join("")), BigInt(`0x${t.hash}`));
      expect(hex(log.encode())).toBe(v.bytes);
    });
  }
});
