// The ABI's test vectors (runtime/abi/vectors.json, generated by the wrela-abi crate from its
// own encoders and decoders): this runtime must make the same of each, down to the messages.

import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { StateHash } from "../src/hash.ts";
import { Lines } from "../src/lines.ts";
import { parseManifest } from "../src/manifest.ts";
import { decode, Sequencer, StreamError } from "../src/stream.ts";

interface ErrorVector {
  kind: string;
  message: string;
}

interface Vectors {
  hashes: { bytes: string; hash: string }[];
  batches: { name: string; bytes: string; outcome: { commands?: unknown[]; error?: ErrorVector } }[];
  sequences: { name: string; bytes: string; error: ErrorVector | null }[];
  manifests: { name: string; json: string; error: string | null }[];
  lines: { name: string; bytes: string; at: [number, string | null][]; error: string | null }[];
}

const vectors: Vectors = JSON.parse(readFileSync(join(import.meta.dir, "../../abi/vectors.json"), "utf8"));

const bytes = (hex: string) => Uint8Array.from(hex.match(/../g) ?? [], (b) => Number.parseInt(b, 16));

/** What a call throws, as the vectors record it. */
function thrown(f: () => unknown): ErrorVector | null {
  try {
    f();
  } catch (e) {
    expect(e).toBeInstanceOf(StreamError);
    return { kind: (e as StreamError).kind, message: (e as Error).message };
  }
  return null;
}

/** A decoded command with its byte arrays as plain arrays, as the vectors hold them. */
const plain = (c: object) =>
  Object.fromEntries(Object.entries(c).map(([k, v]) => [k, v instanceof Uint8Array ? Array.from(v) : v]));

test("state hashes", () => {
  for (const v of vectors.hashes) {
    const h = new StateHash();
    h.update(bytes(v.bytes));
    expect(h.hex()).toBe(v.hash);
  }
});

describe("batches", () => {
  for (const v of vectors.batches) {
    test(v.name, () => {
      let commands: unknown[] | undefined;
      const error = thrown(() => {
        commands = decode(bytes(v.bytes)).map(plain);
      });
      if (v.outcome.error) {
        expect(error).toEqual(v.outcome.error);
      } else {
        expect(error).toBeNull();
        expect(commands).toEqual(v.outcome.commands);
      }
    });
  }
});

describe("sequences", () => {
  for (const v of vectors.sequences) {
    test(v.name, () => {
      const s = new Sequencer();
      const error = thrown(() => {
        for (const c of decode(bytes(v.bytes))) s.step(c);
        s.endFrame();
      });
      expect(error).toEqual(v.error);
    });
  }
});

describe("manifests", () => {
  for (const v of vectors.manifests) {
    test(v.name, () => {
      let error: string | null = null;
      try {
        parseManifest(v.json);
      } catch (e) {
        error = (e as Error).message;
      }
      expect(error).toBe(v.error);
    });
  }
});

describe("line tables", () => {
  for (const v of vectors.lines) {
    test(v.name, () => {
      let lines: Lines | null = null;
      let error: string | null = null;
      try {
        lines = Lines.decode(bytes(v.bytes));
      } catch (e) {
        error = (e as Error).message;
      }
      expect(error).toBe(v.error);
      for (const [offset, loc] of v.at) expect(lines!.at(offset)).toBe(loc);
    });
  }
});
