[package]
name = "wrela_reference_host"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[features]
default = []
inspector = []

[dependencies]
smol_str = "0.3.5"
wrela = { path = "../../compiler" }
wrela_runtime = { path = "../../runtime" }
winit = "0.30.13"
wgpu = "29.0.1"
pollster = "0.4"
