[package]
name = "wrela-sema"
description = "wrela's semantics: modules and names, types, traits, inference, the memory model and GPU rules"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
wrela-diag.workspace = true
wrela-syntax.workspace = true
wrela-abi.workspace = true
elsa = "1.11"

[lints]
workspace = true
