// Generated by tools/generate_unicode.py. Do not edit.
// Unicode 16.0.0; DerivedCoreProperties SHA256: 39d35161f2954497f69e08bdb9e701493f476a3d30222de20028feda36c1dabd
#[rustfmt::skip]
pub const DEFAULT_IGNORABLE_CODE_POINT: &[(u32,u32)] = &[
    (0xAD, 0xAD),
    (0x34F, 0x34F),
    (0x61C, 0x61C),
    (0x115F, 0x1160),
    (0x17B4, 0x17B5),
    (0x180B, 0x180D),
    (0x180E, 0x180E),
    (0x180F, 0x180F),
    (0x200B, 0x200F),
    (0x202A, 0x202E),
    (0x2060, 0x2064),
    (0x2065, 0x2065),
    (0x2066, 0x206F),
    (0x3164, 0x3164),
    (0xFE00, 0xFE0F),
    (0xFEFF, 0xFEFF),
    (0xFFA0, 0xFFA0),
    (0xFFF0, 0xFFF8),
    (0x1BCA0, 0x1BCA3),
    (0x1D173, 0x1D17A),
    (0xE0000, 0xE0000),
    (0xE0001, 0xE0001),
    (0xE0002, 0xE001F),
    (0xE0020, 0xE007F),
    (0xE0080, 0xE00FF),
    (0xE0100, 0xE01EF),
    (0xE01F0, 0xE0FFF),
];
#[rustfmt::skip]
pub fn contains(table: &[(u32,u32)], c: char) -> bool { let n = c as u32; table.binary_search_by(|&(a,b)| if n<a { std::cmp::Ordering::Greater } else if n>b { std::cmp::Ordering::Less } else { std::cmp::Ordering::Equal }).is_ok() }
